[package]
name = "nosleep-ios"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nosleep-types = { path = "../nosleep-types", version = "0.3.0" }
objc = "0.2.7"
